version: "3.8"
services:

  frontend:
    build: 
      context: ./frontend
      target: build
    volumes:
      - "./frontend:/frontend"
    ports:
      - "3000:3000"
  
  backend:
    build: 
      context: ./backend
      target: development
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
    - "./backend:/backend"

  postgres:
    image: postgres:14.3-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
      PGDATA: /data/postgres
    volumes:
      - "postgres:/data/postgres"
      - "./dev/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - "postgres"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: AdminPassword123!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: